# Generated by Django 5.1 on 2024-08-31 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Nome')),
                ('age', models.IntegerField(verbose_name='Idade')),
                ('gender', models.CharField(max_length=155, verbose_name='Genero')),
                ('date_of_birth', models.DateField(verbose_name='Data de nascimento')),
                ('marital_status', models.CharField(max_length=155, verbose_name='Estado Civil')),
                ('education', models.CharField(max_length=155, verbose_name='Escolaridade')),
                ('profession', models.CharField(max_length=155, verbose_name='Profissao')),
            ],
            options={
                'verbose_name': 'Paciente',
            },
        ),
    ]
